[avatar]
  isRemote = false
  url = '/img/avatar.png'

[comments]
  enabled = true
  provider = 'giscus'

[giscus]
  repo = 'mengshitia/hugo-theme-mage'
  repoID = 'R_kgDORIYgWQ'
  category = 'Announcements'
  categoryID = 'DIC_kwDORIYgWc4C56nc'
  mapping = 'pathname'
  strict = true
  reactions = true
  emitMetadata = false
  inputOnTop = true
  [giscus.themes]
    dark = 'catppuccin_frappe'
    light = 'catppuccin_latte'
